name: kleborate
description: Screening Klebsiella genome assemblies for MLST, sub-species, and other related genes of interest
introduction: |
  The `kleborate` module uses [Kleborate](https://github.com/katholt/Kleborate) to screen genome assemblies of 
  _Klebsiella pneumoniae_ and the _Klebsiella pneumoniae_ species complex (KpSC). Kleborate predicts:

  - MLST, species,
  - ICEKp associated virulence loci
  - virulence plasmid associated loci
  - antimicrobial resistance determinants,
  - K (capsule) and O antigen (LPS) serotype prediction.
icon: false
tags:
  - enterics
  - fasta
  - klebsiella
  - serotype
modules:
  - kleborate
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - fasta:
      type: file
      description: A Staphylococcus aureus fasta file.
      pattern: "*.{fna,fna.gz}"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - tsv:
      type: file
      description: A summary of the per-sample kleborate result
      pattern: "*-summary.tab"
  - merged_tsv:
      type: file
      description: A merged TSV of all Kleborate result files
      pattern: "kleborate.tsv"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
citations:
  - kleborate
  - kaptive
