name: checkm
description: Assess the assembly quality of your samples
icon: false
keywords:
  - fasta
  - assembly quality
modules:
  - checkm
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - assembly:
      type: file
      description: The final assembly in FASTA format
      pattern: "*.{fna,fna.gz}"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - results:
      type: file
      description: The full results of CheckM for each sample
      pattern: "*"
  - report:
      type: file
      description: Tab-delimited report of results for a single sample
      pattern: "*.{txt}"
  - merged_reports:
      type: file
      description: Tab-delimited report of results from all samples
      pattern: "*.{txt}"
docs:
  meta:
    title: Bactopia Tools - checkm
    description: |
      A Bactopia Tool which uses CheckM to assess the quality of microbial
      genomes recovered from isolates.
  introduction: |
    The `checkm` module is used [CheckM](https://github.com/Ecogenomics/CheckM) to assess the quality of microbial
    genomes recovered from isolates, single cells, and metagenomes.
  output:
    tree: |
      checkm/
      ├── <SAMPLE_NAME>
      │   ├── bins/
      │   ├── logs
      │   │   └── checkm
      │   │       ├── nf-checkm.{begin,err,log,out,run,sh,trace}
      │   │       ├── checkm.log
      │   │       └── versions.yml
      │   ├── storage/
      │   ├── lineage.ms
      │   ├── <SAMPLE_NAME>-genes.aln
      │   └── <SAMPLE_NAME>-results.txt
      ├── checkm.tsv
      ├── logs
      │   ├── csvtk_concat
      │   │   ├── nf-csvtk_concat.{begin,err,log,out,run,sh,trace}
      │   │   └── versions.yml
      │   └── custom_dumpsoftwareversions
      │       ├── nf-custom_dumpsoftwareversions.{begin,err,log,out,run,sh,trace}
      │       └── versions.yml
      ├── nf-reports
      │   ├── checkm-dag.dot
      │   ├── checkm-report.html
      │   ├── checkm-timeline.html
      │   └── checkm-trace.txt
      ├── software_versions.yml
      └── software_versions_mqc.yml
    add_note: false
    folders:
      - name: CheckM
        description: |
          Below is a description of the _per-sample_ results from [CheckM](https://github.com/Ecogenomics/CheckM).
        table: |
          | Filename | Description |
          |----------|-------------|
          | bins/ | A folder with inputs (e.g. proteins) for processing by `CheckM`  |
          | storage/ | A folder with intermediate results from `CheckM` processing |
          | lineage.ms | Output file describing marker set for each bin |
          | &lt;SAMPLE_NAME&gt;-genes.aln | Alignment of multi-copy genes and their AAI identity |
          | &lt;SAMPLE_NAME&gt;-results.txt | Final results of [CheckM's lineage_wf](https://github.com/Ecogenomics/CheckM/wiki/Workflows#lineage-specific-workflow) |
  citations:
    - checkm
