name: eggnog
description: Functional annotation of proteins using orthologous groups and phylogenies
introduction: |
  The `eggnog` module uses [eggNOG-mapper](https://github.com/eggnogdb/eggnog-mapper) to assign 
  functional annotation to protein sequences. eggNOG-mapper uses orthologous groups and phylogenies
  from the eggNOG database to more precisely functionally annotate than traditional homology methods.
icon: false
tags:
  - annotation
  - fasta
  - prokaryote
modules:
  - eggnog_download
  - eggnog_mapper
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - fasta:
      type: file
      description: FASTA assembly file
      pattern: "*.{fasta,fasta.gz,fa,fa.gz,fna,fna.gz}"
  - db:
      type: folder
      description: directory containing eggNOG databases
      pattern: "*"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
citations:
  - eggnog_mapper
  - eggnog_db
