name: merlin
description: MinmER assisted species-specific bactopia tool seLectIoN
keywords:
  - serotype
  - species-specific
modules:
  - mash_dist
  - agrvate
  - ectyper
  - emmtyper
  - hicap
  - kleborate
  - legsta
  - lissero
  - meningotype
  - ngmaster
  - seqsero2
  - sistr
  - spatyper
  - staphopiasccmec
  - tbprofiler_profile
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - INPUT_FILE:
      type: file
      description: Description of input file

output:
  - FILETYPE:
      type: file
      description: Output file description
      pattern: '*.{bam}'
  - versions:
      type: file
      description: File containing software versions
      pattern: 'versions.yml'
