name: merlin
description: MinmER assisted species-specific bactopia tool seLectIoN
introduction: |
  The `merlin` subworkflow uses Mash distances to automatically select species specific tools to execute.
keywords:
  - serotype
  - species-specific
modules:
  - mash_dist
  - agrvate
  - ectyper
  - emmtyper
  - hicap
  - hpsuissero
  - genotyphi
  - kleborate
  - legsta
  - lissero
  - meningotype
  - ngmaster
  - pasty
  - pbptyper
  - seqsero2
  - shigatyper
  - shigeifinder
  - sistr
  - spatyper
  - staphopiasccmec
  - ssuissero
  - tbprofiler_profile
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - INPUT_FILE:
      type: file
      description: Description of input file
output_tree: "example output from tree"
output:
  - FILETYPE:
      type: file
      description: Output file description
      pattern: '*.{bam}'
  - versions:
      type: file
      description: File containing software versions
      pattern: 'versions.yml'

docs:
  meta:
    title: merlin
    description: >-
      A Bactopia Tool for the automatic selection and executions of 
      species-specific tools.
  introduction: |
    _MinmER assisted species-specific bactopia tool seLectIoN_, or Merlin, uses distances based
    on the RefSeq sketch downloaded by `bactopia datasets` to automatically run species-specific tools.
    
    Currently Merlin knows 16 spells for which cover the following:
    
    | Genus/Species | Tools |
    |---------------|-------|
    | Escherichia / Shigella   | [ECTyper](/bactopia-tools/ectyper/), [ShigaTyper](/bactopia-tools/shigtyper/), [ShigEiFinder](/bactopia-tools/shigeityper/)  |
    | Haemophilus   | [hicap](/bactopia-tools/hicap/), [HpsuisSero](/bactopia-tools/ssuissero/) |
    | Klebsiella | [Kleborate](/bactopia-tools/kleborate/) |
    | Legionella | [legsta](/bactopia-tools/legsta/) |
    | Listeria | [LisSero](/bactopia-tools/lissero/) |
    | Mycobacterium | [TBProfiler](/bactopia-tools/tbprofiler/) |
    | Neisseria | [meningotype](/bactopia-tools/meningotype/), [ngmaster](/bactopia-tools/ngmaster/) |
    | Pseudomonas | [pasty](/bactopia-tools/pasty/) |
    | Salmonella | [SeqSero2](/bactopia-tools/seqsero2/), [SISTR](/bactopia-tools/sistr/) |
    | Staphylococcus | [AgrVATE](/bactopia-tools/agrvate/), [spaTyper](/bactopia-tools/spatyper/), [staphopia-sccmec](/bactopia-tools/staphopiasccmec/) |
    | Streptococcus | [emmtyper](/bactopia-tools/emmtyper/), [pbptyper](/bactopia-tools/pbptyper/), [SsuisSero](/bactopia-tools/ssuissero/) |
  
    Merlin is avialable as an independent Bactopia Tool, or in the Bactopia with the `--ask_merlin` parameter. Even better,
    if you want to force Merlin to execute all species-specific tools (no matter the distance), you can use `--full_merlin`.
    Then all the spells will be unleashed!
  output:
    tree: |
      merlin/
      ├── <SAMPLE_NAME>
      │   ├── agrvate
      │   │   ├── <SAMPLE_NAME>-agr_gp.tab
      │   │   ├── <SAMPLE_NAME>-blastn_log.txt
      │   │   └── <SAMPLE_NAME>-summary.tab
      │   ├── ectyper
      │   │   ├── <SAMPLE_NAME>.tsv
      │   │   └── blast_output_alleles.txt
      │   ├── emmtyper
      │   │   └── <SAMPLE_NAME>.tsv
      │   ├── hicap
      │   │   └── <SAMPLE_NAME>.tsv
      │   ├── hpsuissero
      │   │   └── <SAMPLE_NAME>_serotyping_res.tsv
      │   ├── kleborate
      │   │   └── <SAMPLE_NAME>.results.txt
      │   ├── legsta
      │   │   └── <SAMPLE_NAME>.tsv
      │   ├── lissero
      │   │   └── <SAMPLE_NAME>.tsv
      │   ├── logs
      │   │   └── <BACTOPIA_TOOL>
      │   │       ├── nf-<BACTOPIA_TOOL>.{begin,err,log,out,run,sh,trace}
      │   │       └── versions.yml
      │   ├── mashdist
      │   │   └── <SAMPLE_NAME>-dist.txt
      │   ├── meningotype
      │   │   └── <SAMPLE_NAME>.tsv
      │   ├── ngmaster
      │   │   └── <SAMPLE_NAME>.tsv
      │   ├── seqsero2
      │   │   ├── <SAMPLE_NAME>_log.txt
      │   │   ├── <SAMPLE_NAME>_result.tsv
      │   │   └── <SAMPLE_NAME>_result.txt
      │   ├── sistr
      │   │   ├── <SAMPLE_NAME>-allele.fasta.gz
      │   │   ├── <SAMPLE_NAME>-allele.json.gz
      │   │   ├── <SAMPLE_NAME>-cgmlst.csv
      │   │   └── <SAMPLE_NAME>.tsv
      │   ├── spatyper
      │   │   └── <SAMPLE_NAME>.tsv
      │   ├── ssuissero
      │   │   └── <SAMPLE_NAME>_serotyping_res.tsv
      │   ├── staphopiasccmec
      │   │   └── <SAMPLE_NAME>.tsv
      │   └── tbprofiler
      │       ├── <SAMPLE_NAME>.results.csv
      │       ├── <SAMPLE_NAME>.results.json
      │       ├── <SAMPLE_NAME>.results.txt
      │       ├── bam
      │       │   └── <SAMPLE_NAME>.bam
      │       └── vcf
      │           └── <SAMPLE_NAME>.targets.csq.vcf.gz
      ├── logs
      │   ├── csvtk_concat
      │   │   └── <BACTOPIA_TOOL>
      │   │       ├── nf-csvtk_concat.{begin,err,log,out,run,sh,trace}
      │   │       └── versions.yml
      │   └── custom_dumpsoftwareversions
      │       ├── nf-custom_dumpsoftwareversions.{begin,err,log,out,run,sh,trace}
      │       └── versions.yml
      ├── nf-reports
      │   ├── merlin-dag.dot
      │   ├── merlin-report.html
      │   ├── merlin-timeline.html
      │   └── merlin-trace.txt
      ├── agrvate.tsv
      ├── ectyper.tsv
      ├── emmtyper.tsv
      ├── hicap.tsv
      ├── hpsuissero.tsv
      ├── kleborate.tsv
      ├── legsta.tsv
      ├── lissero.tsv
      ├── meningotype.tsv
      ├── ngmaster.tsv
      ├── seqsero2.tsv
      ├── sistr.tsv
      ├── software_versions.yml
      ├── software_versions_mqc.yml
      ├── spatyper.tsv
      ├── ssuissero.tsv
      └── staphopiasccmec.tsv
    add_note: true
    folders:
      - name: Top Level
        description: |
          Below are results that are in the base directory.
        table: |
          | Filename    | Description |
          |-------------|-------------|
          | agrvate.tsv | A merged TSV file with `AgrVATE` results from all samples |
          | ectyper.tsv | A merged TSV file with `ECTyper` results from all samples |
          | emmtyper.tsv | A merged TSV file with `emmtyper` results from all samples |
          | hicap.tsv  | A merged TSV file with `hicap` results from all samples |
          | hpsuissero.tsv | A merged TSV file with `HpsuisSero` results from all samples |
          | kleborate.tsv | A merged TSV file with `Kleborate` results from all samples |
          | legsta.tsv  | A merged TSV file with `legsta` results from all samples |
          | lissero.tsv  | A merged TSV file with `LisSero` results from all samples |
          | meningotype.tsv  | A merged TSV file with `meningotype` results from all samples |
          | ngmaster.tsv  | A merged TSV file with `ngmaster` results from all samples |
          | seqsero2.tsv  | A merged TSV file with `seqsero2` results from all samples |
          | sistr.tsv  | A merged TSV file with `SISTR` results from all samples |
          | spatyper.tsv  | A merged TSV file with `spaTyper` results from all samples |
          | ssuissero.tsv  | A merged TSV file with `SsuisSero` results from all samples |
          | staphopiasccmec.tsv  | A merged TSV file with `staphopia-sccmec` results from all samples |
      - name: AgrVATE
        description: |
          Below is a description of the _per-sample_ results from [AgrVATE](https://github.com/VishnuRaghuram94/AgrVATE).
        table: |
          | Extension       | Description |
          |-----------------|-------------|
          | -agr_gp.tab     | Detailed report for _agr_ kmer matches |
          | -blastn_log.txt | Log files from programs called by `AgrVATE` |
          | -summary.tab    | A final summary report for _agr_ typing |
      - name: ECTyper
        description: |
          Below is a description of the _per-sample_ results from [ECTyper](https://github.com/phac-nml/ecoli_serotyping).
        table: |
          | Filename                 | Description |
          |--------------------------|-------------|
          | &lt;SAMPLE_NAME&gt;.tsv  | A tab-delimited file with `ECTyper` result, see [ECTyper - Report format](https://github.com/phac-nml/ecoli_serotyping#report-format) for details  |
          | blast_output_alleles.txt | Allele report generated from BLAST results |
      - name: emmtyper
        description: |
          Below is a description of the _per-sample_ results from [emmtyper](https://github.com/MDU-PHL/emmtyper).
        table: |
          | Filename                 | Description |
          |--------------------------|-------------|
          | &lt;SAMPLE_NAME&gt;.tsv  | A tab-delimited file with `emmtyper` result, see [emmtyper - Result format](https://github.com/MDU-PHL/emmtyper#result-format) for details  |
      - name: hicap
        description: |
          Below is a description of the _per-sample_ results from [hicap](https://github.com/scwatts/hicap).
        table: |
          | Filename                 | Description |
          |--------------------------|-------------|
          | &lt;SAMPLE_NAME&gt;.gbk  | GenBank file and cap locus annotations |
          | &lt;SAMPLE_NAME&gt;.svg  | Visualization of annotated cap locus |
          | &lt;SAMPLE_NAME&gt;.tsv  | A tab-delimited file with `hicap` results |
      - name: HpsuisSero
        description: |
          Below is a description of the _per-sample_ results from [HpsuisSero](https://github.com/jimmyliu1326/HpsuisSero).
        table: |
          | Filename                 | Description |
          |--------------------------|-------------|
          | &lt;SAMPLE_NAME&gt;_serotyping_res.tsv  | A tab-delimited file with `HpsuisSero` result |
      - name: Kleborate
        description: |
          Below is a description of the _per-sample_ results from [Kleborate](https://github.com/katholt/Kleborate).
        table: |
          | Filename                 | Description |
          |--------------------------|-------------|
          | &lt;SAMPLE_NAME&gt;.results.tsv  | A tab-delimited file with `Kleborate` result, see [Kleborate - Example output](https://github.com/katholt/Kleborate/wiki/Tests-and-example-outputs#example-output) for more details |
      - name: legsta
        description: |
          Below is a description of the _per-sample_ results from [legsta](https://github.com/tseemann/legsta).
        table: |
          | Filename                 | Description |
          |--------------------------|-------------|
          | &lt;SAMPLE_NAME&gt;.tsv  | A tab-delimited file with `legsta` result, see [legsta - Output](https://github.com/tseemann/legsta#output) for more details |
      - name: LisSero
        description: |
          Below is a description of the _per-sample_ results from [LisSero](https://github.com/MDU-PHL/LisSero).
        table: |
          | Filename                 | Description |
          |--------------------------|-------------|
          | &lt;SAMPLE_NAME&gt;.tsv  | A tab-delimited file with `LisSero` results |
      - name: Mash
        description: |
          Below is a description of the _per-sample_ results from [Mash](https://github.com/marbl/Mash).
        table: |
          | Filename                 | Description |
          |--------------------------|-------------|
          | &lt;SAMPLE_NAME&gt;-dist.txt  | A tab-delimited file with `mash dist` results |
      - name: meningotype
        description: |
          Below is a description of the _per-sample_ results from [meningotype](https://github.com/MDU-PHL/meningotype) .
        table: |
          | Filename                 | Description |
          |--------------------------|-------------|
          | &lt;SAMPLE_NAME&gt;.tsv  | A tab-delimited file with `meningotype` result |
      - name: ngmaster
        description: |
          Below is a description of the _per-sample_ results from [ngmaster](https://github.com/MDU-PHL/ngmaster).
        table: |
          | Filename                 | Description |
          |--------------------------|-------------|
          | &lt;SAMPLE_NAME&gt;.tsv  | A tab-delimited file with `ngmaster` results |
      - name: SeqSero2
        description: |
          Below is a description of the _per-sample_ results from [SeqSero2](https://github.com/denglab/SeqSero2).
        table: |
          | Filename                 | Description |
          |--------------------------|-------------|
          | &lt;SAMPLE_NAME&gt;.tsv  | A tab-delimited file with `SeqSero2` results |
          | &lt;SAMPLE_NAME&gt;.txt  | A text file with key-value pairs of `SeqSero2` results |
      - name: SISTR
        description: |
          Below is a description of the _per-sample_ results from [SISTR](https://github.com/phac-nml/sistr_cmd).
        table: |
          | Filename                 | Description |
          |--------------------------|-------------|
          | &lt;SAMPLE_NAME&gt;-allele.fasta.gz  | A FASTA file of the cgMLST allele search results  |
          | &lt;SAMPLE_NAME&gt;-allele.json.gz  | JSON formated cgMLST allele search results, see [SISTR - cgMLST search results](https://github.com/phac-nml/sistr_cmd#cgmlst-allele-search-results) for more details |
          | &lt;SAMPLE_NAME&gt;-cgmlst.csv  | A comma-delimited summary of the cgMLST allele search results |
          | &lt;SAMPLE_NAME&gt;.tsv  | A tab-delimited file with `SISTR` results, see [SISTR - Primary results](https://github.com/phac-nml/sistr_cmd#primary-results-output--o-sistr-results) for more details |
      - name: spaTyper
        description: |
          Below is a description of the _per-sample_ results from [spaTyper](https://github.com/HCGB-IGTP/spaTyper).
        table: |
          | Filename                 | Description |
          |--------------------------|-------------|
          | &lt;SAMPLE_NAME&gt;.tsv  | A tab-delimited file with `spaTyper` results |
      - name: SsuisSero
        description: |
          Below is a description of the _per-sample_ results from [SsuisSero](https://github.com/jimmyliu1326/SsuisSero).
        table: |
          | Filename                 | Description |
          |--------------------------|-------------|
          | &lt;SAMPLE_NAME&gt;_serotyping_res.tsv  | A tab-delimited file with `SsuisSero` results |
      - name: staphopia-sccmec
        description: |
          Below is a description of the _per-sample_ results from [staphopia-sccmec](https://github.com/staphopia/staphopia-sccmec).
        table: |
          | Filename                 | Description |
          |--------------------------|-------------|
          | &lt;SAMPLE_NAME&gt;.tsv  | A tab-delimited file with `staphopia-sccmec` results |
      - name: TBProfiler
        description: |
          Below is a description of the _per-sample_ results from [TBProfiler](https://github.com/jodyphelan/TBProfiler).
        table: |
          | Filename                 | Description |
          |--------------------------|-------------|
          | &lt;SAMPLE_NAME&gt;.results.csv  | A CSV formated `TBProfiler` result file of resistance and strain type |
          | &lt;SAMPLE_NAME&gt;.results.json  | A JSON formated `TBProfiler` result file of resistance and strain type |
          | &lt;SAMPLE_NAME&gt;.results.txt  | A text file with `TBProfiler` results |
          | &lt;SAMPLE_NAME&gt;.bam  |BAM file with alignment details |
          | &lt;SAMPLE_NAME&gt;.targets.csq.vcf.gz | VCF with variant info again refernce genomes |
  citations:
    - agrvate
    - csvtk
    - ectyper
    - emmtyper
    - hicap
    - hpsuissero
    - genotyphi
    - kleborate
    - legsta
    - lissero
    - mash
    - meningotype
    - mykrobe
    - ngmaster
    - pasty
    - pbptyper
    - seqsero2
    - shigatyper
    - shigeifinder
    - sistr
    - spatyper
    - staphopiasccmec
    - ssuissero
    - tbprofiler
