name: hicap
description: Identify cap locus serotype and structure in your _Haemophilus influenzae_ assemblies
icon: false
tags:
  - capsule
  - Haemophilus influenzae
  - serotype
modules:
  - hicap
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - fasta:
      type: file
      description: A Haemophilus influenzae fasta file.
      pattern: "*.{fna,fna.gz}"
  - database_dir:
      type: directory
      description: Optional - Directory containing locus database
      pattern: "*/*"
  - model_fp:
      type: file
      description: Optional - Prodigal model to use for gene prediction
      pattern: "*.{bin}"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - tsv:
      type: file
      description: A summary of the per-sample hicap result
      pattern: "*.tsv"
  - merged_tsv:
      type: file
      description: A merged TSV of all hicap result files
      pattern: "hicap.tsv"
  - gbk:
      type: file
      description: GenBank file and cap locus annotations
      pattern: "*.gbk"
  - svg:
      type: file
      description: Visualization of annotated cap locus
      pattern: "*.svg"
  - versions:
      type: file
      description: File containing software versions
      pattern: 'versions.yml'
docs:
  meta:
    title: Bactopia Tools - hicap
    description: >-
      A Bactopia Tool which uses hicap along wih an assembly for the _in silico_ typing of
      the _Haemophilus influenzae_ cap locus.
  introduction: |
    The `hicap` module uses [hicap](https://github.com/scwatts/hicap) along wih an assembly for
    the _in silico_ typing of the _Haemophilus influenzae_ cap locus.
  output:
    tree: |
      hicap/
      ├── <SAMPLE_NAME>
      │   ├── <SAMPLE_NAME>.gbk
      │   ├── <SAMPLE_NAME>.svg
      │   ├── <SAMPLE_NAME>.tsv
      │   └── logs
      │       └── hicap
      │           ├── nf-hicap.{begin,err,log,out,run,sh,trace}
      ├── logs
      │   ├── csvtk_concat
      │   │   ├── nf-csvtk_concat.{begin,err,log,out,run,sh,trace}
      │   │   └── versions.yml
      │   └── custom_dumpsoftwareversions
      │       ├── nf-custom_dumpsoftwareversions.{begin,err,log,out,run,sh,trace}
      │       └── versions.yml
      ├── nf-reports
      │   ├── hicap-dag.dot
      │   ├── hicap-report.html
      │   ├── hicap-timeline.html
      │   └── hicap-trace.txt
      ├── hicap.tsv
      ├── software_versions.yml
      └── software_versions_mqc.yml
    add_note: true
    folders:
      - name: Top Level
        description: |
          Below are results that are in the base directory.
        table: |
          | Filename    | Description |
          |-------------|-------------|
          | hicap.tsv  | A merged TSV file with `hicap` results from all samples |
      - name: hicap
        description: |
          Below is a description of the _per-sample_ results from [hicap](https://github.com/scwatts/hicap).
        table: |
          | Filename                 | Description |
          |--------------------------|-------------|
          | &lt;SAMPLE_NAME&gt;.gbk  | GenBank file and cap locus annotations |
          | &lt;SAMPLE_NAME&gt;.svg  | Visualization of annotated cap locus |
          | &lt;SAMPLE_NAME&gt;.tsv  | A tab-delimited file with `hicap` results |
  citations:
    - hicap
