name: tbprofiler
description: Detect resistance and lineages of _Mycobacterium tuberculosis_ genomes
introduction: |
  The `tbprofiler` module uses [TBProfiler](https://github.com/jodyphelan/TBProfiler) for 
  for profiling reads to determine resistance and _Mycobacterium tuberculosis_ strain type.
icon: false
tags:
  - Mycobacterium tuberculosis
  - resistance
  - serotype
modules:
  - tbprofiler_profile
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - reads:
      type: file
      description: FASTQ file
      pattern: "*.{fastq.gz,fq.gz}"
output:
  - versions:
      type: file
      description: File containing software versions
      pattern: 'versions.yml'
  - bam:
      type: file
      description: BAM file with alignment details
      pattern: "*.bam"
  - csv:
      type: file
      description: Optional CSV formated result file of resistance and strain type
      pattern: "*.csv"
  - json:
      type: file
      description: JSON formated result file of resistance and strain type
      pattern: "*.json"
  - txt:
      type: file
      description: Optional text file of resistance and strain type
      pattern: "*.txt"
  - vcf:
      type: file
      description: VCF with variant info again refernce genomes
      pattern: "*.vcf"
citations:
  - tbprofiler
