name: meningotype
description: Serotyping of Neisseria meningitidis
introduction: |
  The `meningotype` module uses [meningotype](https://github.com/MDU-PHL/meningotype) 
  for _in silico_ typing of _Neisseria meningitidis_ genomes. It uses the contigs from 
  assemblies to determine the serotype, MLST, finetyping  (_porA_, _fetA_, _porB_), and 
  Bexsero antigen sequence typing (BAST) (_fHbp_, _NHBA_, _NadA_, _PorA_).
icon: false
tags:
  - fasta
  - Neisseria meningitidis
  - serotype
modules:
  - meningotype
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - fasta:
      type: file
      description: A Neisseria meningitidis fasta file.
      pattern: "*.{fna,fna.gz}"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - tsv:
      type: file
      description: A summary of the per-sample meningotype result
      pattern: "*.tsv"
  - merged_tsv:
      type: file
      description: A merged TSV of all meningotype result files
      pattern: "meningotype.tsv"
  - versions:
      type: file
      description: File containing software versions
      pattern: 'versions.yml'
citations:
  - meningotype
