name: amrfinderplus
description: Identify antimicrobial resistance in genes or proteins

icon: false
tags:
  - antimicrobial resistance
  - fasta
modules:
  - amrfinderplus
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - fasta:
      type: file
      description: |
        Assembly and predicted proteins to screen
  - db:
      type: file
      description: |
        AMRFinder+ database create by this workflow or bactopia datasets
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - gene_tsv:
      type: file
      description: AMRFinder+ final gene report
      pattern: "*-genes.tsv"
  - merged_gene_tsv:
      type: file
      description: A merged TSV of all AMRFinder+ gene reports
      pattern: "amrfinderplus-genes.tsv"
  - proteins_tsv:
      type: file
      description: AMRFinder+ final protein report
      pattern: "*-proteins.tsv"
  - merged_proteins_tsv:
      type: file
      description: A merged TSV of all AMRFinder+ protein reports
      pattern: "amrfinderplus-proteins.tsv"
  - mutation_reports:
      type: file
      description: Report of organism-specific point-mutations
      pattern: "*-mutations.tsv"
docs:
  meta:
    title: amrfinderplus
    description: >-
      A Bactopia Tool which uses AMRFinder+ to screen assemblies and proteins
      for antimicrobial resistance and virulence genes.
  introduction: |
    The `amrfinderplus` module uses [AMRFinder+](https://github.com/ncbi/amr) to screen assemblies and proteins
    for antimicrobial resistance and virulence genes.
  output:
    tree: |
      amrfinderplus/
      ├── SRX4563671
      │   ├── SRX4563671-genes.tsv
      │   ├── SRX4563671-proteins.tsv
      │   └── logs
      │       └── amrfinderplus
      │           ├── nf-amrfinderplus.{begin,err,log,out,run,sh,trace}
      │           └── versions.yml
      ├── logs
      │   ├── amrfinderplus
      │   │   ├── nf-amrfinderplus.{begin,err,log,out,run,sh,trace}
      │   │   └── versions.yml
      │   ├── csvtk_concat
      │   │   ├── nf-csvtk_concat.{begin,err,log,out,run,sh,trace}
      │   │   └── versions.yml
      │   └── custom_dumpsoftwareversions
      │       ├── nf-custom_dumpsoftwareversions.{begin,err,log,out,run,sh,trace}
      │       └── versions.yml
      ├── nf-reports
      │   ├── amrfinderplus-dag.dot
      │   ├── amrfinderplus-report.html
      │   ├── amrfinderplus-timeline.html
      │   └── amrfinderplus-trace.txt
      ├── amrfinderdb.tar.gz
      ├── amrfinderplus-genes.tsv
      ├── amrfinderplus-proteins.tsv
      ├── software_versions.yml
      └── software_versions_mqc.yml
    add_note: false
    folders:
      - name: Top Level
        description: |
          Below are results that are in the base directory.
        table: |
          | Filename                   | Description |
          |----------------------------|-------------|
          | amrfinderdb.tar.gz         | A tarball of the `AMRFinder+` database used during analysis |
          | amrfinderplus-genes.tsv    | A merged TSV file with `AMRFinder+` results using nucleotide inputs |
          | amrfinderplus-proteins.tsv | A merged TSV file with `AMRFinder+` results using protein inputs |
      - name: AMRFinder+
        description: |
          Below is a description of the _per-sample_ results from [AMRFinder+](https://github.com/ncbi/amr).
        table: |
          | Extension     | Description |
          |---------------|-------------|
          | -genes.tsv    | A TSV file with `AMRFinder+` results using nucleotide inputs |
          | -proteins.tsv | A TSV file with `AMRFinder+` results using protein inputs |
  citations:
    - amrfinderplus
