{% set version = '2.1.0' %}

package:
  name: bactopia
  version: {{ version }}

source:
  url: https://github.com/bactopia/bactopia/archive/refs/heads/dev.zip

requirements:
  host:
    - pip
    - python >3.6,<3.10
  run:
    - ariba >=2.14.6
    - bakta >=1.4
    - blast >=2.11.0
    - cd-hit
    - conda
    - coreutils
    - executor
    - gsl <=2.6
    - mamba
    - mash
    - ncbi-amrfinderplus 3.10.23
    - ncbi-genome-download
    - nextflow >=21.10.0
    - pytest
    - pytest-workflow
    - python >3.6,<3.10
    - requests
    - tbb 2020.2
    - sed
    - unzip
    - wget

test:
  commands:
    - "bactopia --version"
    - "bactopia datasets --help"
    - "bactopia prepare"
    - "bactopia search"
    - "bactopia-summary --help"

about:
  home: https://bactopia.github.io/
  license: MIT
  license_file: LICENSE
  summary: Bactopia is a flexible pipeline for complete analysis of bacterial genomes.
  dev_url: https://github.com/bactopia/bactopia/

extra:
  recipe-maintainers:
    - rpetit3
  identifiers:
    - biotools:bactopia
    - doi:10.1128/mSystems.00190-20
