name: hpsuissero
description: Serotype prediction of _Haemophilus parasuis_ assemblies
keywords:
  - bacteria
  - fasta
  - haemophilus
modules:
  - hpsuissero
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - fasta:
      type: file
      description: The final assembly in FASTA format
      pattern: "*.{fna,fna.gz}"
output:
  - tsv:
      type: file
      description: A summary of the per-sample serotype predictions
      pattern: "*.tsv"
  - merged_tsv:
      type: file
      description: A merged TSV of all serotype predictions
      pattern: "ectyper.tsv"
  - versions:
      type: file
      description: File containing software versions
      pattern: 'versions.yml'

docs:
  meta:
    title: Bactopia Tools - hpsuissero
    description: >-
      A Bactopia Tool which uses HpsuisSero to predict the serotype of _Haemophilus parasuis_
      assemblies.
  introduction: |
    The `hpsuissero` module uses [HpsuisSero](https://github.com/jimmyliu1326/HpsuisSero) to predict
    the serotype of _Haemophilus parasuis_ assemblies.
  output:
    tree: |
      hpsuissero/
      ├── <SAMPLE_NAME>
      │   ├── <SAMPLE_NAME>_serotyping_res.tsv
      │   └── logs
      │       └── hpsuissero
      │           ├── nf-hpsuissero.{begin,err,log,out,run,sh,trace}
      │           └── versions.yml
      ├── logs
      │   ├── csvtk_concat
      │   │   ├── nf-csvtk_concat.{begin,err,log,out,run,sh,trace}
      │   │   └── versions.yml
      │   └── custom_dumpsoftwareversions
      │       ├── nf-custom_dumpsoftwareversions.{begin,err,log,out,run,sh,trace}
      │       └── versions.yml
      ├── nf-reports
      │   ├── hpsuissero-dag.dot
      │   ├── hpsuissero-report.html
      │   ├── hpsuissero-timeline.html
      │   └── hpsuissero-trace.txt
      ├── hpsuissero.tsv
      ├── software_versions.yml
      └── software_versions_mqc.yml
    add_note: true
    folders:
      - name: Top Level
        description: |
          Below are results that are in the base directory.
        table: |
          | Filename    | Description |
          |-------------|-------------|
          | hpsuissero.tsv | A merged TSV file with `HpsuisSero` results from all samples |
      - name: HpsuisSero
        description: |
          Below is a description of the _per-sample_ results from [HpsuisSero](https://github.com/jimmyliu1326/HpsuisSero).
        table: |
          | Filename                 | Description |
          |--------------------------|-------------|
          | &lt;SAMPLE_NAME&gt;_serotyping_res.tsv  | A tab-delimited file with `HpsuisSero` result |
citations:
  - hpsuissero
