name: ssuissero
description: Serotype prediction of _Streptococcus suis_ assemblies
keywords:
  - bacteria
  - fasta
  - streptococcus
modules:
  - ssuissero
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - fasta:
      type: file
      description: The final assembly in FASTA format
      pattern: "*.{fna,fna.gz}"
output:
  - tsv:
      type: file
      description: A summary of the per-sample serotype predictions
      pattern: "*.tsv"
  - merged_tsv:
      type: file
      description: A merged TSV of all serotype predictions
      pattern: "ectyper.tsv"
  - versions:
      type: file
      description: File containing software versions
      pattern: 'versions.yml'
docs:
  meta:
    title: ssuissero
    description: >-
      A Bactopia Tool which uses SsuisSero to predict the serotype of
      _Streptococcus suis_ assemblies.
  introduction: |
    The `ssuissero` module uses [SsuisSero](https://github.com/jimmyliu1326/SsuisSero) to predict
    the serotype of _Streptococcus suis_ assemblies.
  output:
    tree: |
      ssuissero/
      ├── <SAMPLE_NAME>
      │   ├── <SAMPLE_NAME>_serotyping_res.tsv
      │   └── logs
      │       └── ssuissero
      │           ├── nf-ssuissero.{begin,err,log,out,run,sh,trace}
      │           └── versions.yml
      ├── logs
      │   ├── csvtk_concat
      │   │   ├── nf-csvtk_concat.{begin,err,log,out,run,sh,trace}
      │   │   └── versions.yml
      │   └── custom_dumpsoftwareversions
      │       ├── nf-custom_dumpsoftwareversions.{begin,err,log,out,run,sh,trace}
      │       └── versions.yml
      ├── nf-reports
      │   ├── ssuissero-dag.dot
      │   ├── ssuissero-report.html
      │   ├── ssuissero-timeline.html
      │   └── ssuissero-trace.txt
      ├── software_versions.yml
      ├── software_versions_mqc.yml
      └── ssuissero.tsv
    add_note: true
    folders:
      - name: Top Level
        description: |
          Below are results that are in the base directory.
        table: |
          | Filename    | Description |
          |-------------|-------------|
          | ssuissero.tsv  | A merged TSV file with `SsuisSero` results from all samples |
      - name: SsuisSero
        description: |
          Below is a description of the _per-sample_ results from [SsuisSero](https://github.com/jimmyliu1326/SsuisSero).
        table: |
          | Filename                 | Description |
          |--------------------------|-------------|
          | &lt;SAMPLE_NAME&gt;_serotyping_res.tsv  | A tab-delimited file with `SsuisSero` results |
  citations:
    - ssuissero
