name: snippy
description: Rapid variant calling from sequence reads
introduction: |
  The `snippy` module uses...
keywords:
  - TAGS
modules:
  - snippy_run
  - snippy_core
  - gubbins
  - iqtree
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - INPUT_FILE:
      type: file
      description: Description of input file
output_tree: |
  ```  ```
output:
  - FILETYPE:
      type: file
      description: Output file description
      pattern: '*.{bam}'
  - versions:
      type: file
      description: File containing software versions
      pattern: 'versions.yml'
citations:
  - gubbins
  - iqtree
  - iqtree_modelfinder
  - iqtree_ufboot
  - snippy
