name: staphopiasccmec
description: Primer based SCCmec typing of Staphylococcus aureus genomes
keywords:
  - amr
  - fasta
  - sccmec
  - Staphylococcus aureus
modules:
  - staphopiasccmec
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - fasta:
      type: file
      description: FASTA assembly file
      pattern: "*.{fasta,fasta.gz,fa,fa.gz,fna,fna.gz}"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software versions
      pattern: 'versions.yml'
  - tsv:
      type: file
      description: Per-sample summary of the staphopia-sccmec assessement
      pattern: "*.tsv"
  - merged_tsv:
      type: file
      description: A merged summary of the staphopia-sccmec assessement
      pattern: "staphopiasccmec.tsv"
