name: rgi
description: Predict antibiotic resistance from assemblies
keywords:
  - bacteria
  - fasta
  - antibiotic resistance
modules:
  - rgi
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - fasta:
      type: file
      description: The final assembly in FASTA format
      pattern: "*.{fna,fna.gz}"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - json:
      type: file
      description: JSON report of results for a single sample
      pattern: "*.{txt}"
  - tsv:
      type: file
      description: Tab-delimited report of results for a single sample
      pattern: "*.{txt}"
  - merged_tsv:
      type: file
      description: Tab-delimited report of results from all samples
      pattern: "*.{txt}"
  - heatmap:
      type: file
      description: Heatmap representations as text and images
      pattern: "*.{csv,eps,png}"
docs:
  introduction: |
    The `rgi` module uses [Resistance Gene Identifier (RGI)](https://github.com/arpcard/rgi) to identify antibiotic
    resistance genes in assemblies.
  output:
    tree: |
      rgi/
      ├── <SAMPLE_NAME>
      │   ├── <SAMPLE_NAME>.json
      │   ├── <SAMPLE_NAME>.txt
      │   └── logs
      │       └── rgi
      │           ├── nf-rgi.{begin,err,log,out,run,sh,trace}
      │           └── versions.yml
      ├── logs
      │   ├── csvtk_concat
      │   │   ├── nf-csvtk_concat.{begin,err,log,out,run,sh,trace}
      │   │   └── versions.yml
      │   ├── custom_dumpsoftwareversions
      │   │   ├── nf-custom_dumpsoftwareversions.{begin,err,log,out,run,sh,trace}
      │   │   └── versions.yml
      │   └── rgi_heatmap
      │       ├── nf-rgi_heatmap.{begin,err,log,out,run,sh,trace}
      │       └── versions.yml
      ├── nf-reports
      │   ├── rgi-dag.dot
      │   ├── rgi-report.html
      │   ├── rgi-timeline.html
      │   └── rgi-trace.txt
      ├── rgi-20.{csv,eps,png}
      ├── rgi.tsv
      ├── software_versions.yml
      └── software_versions_mqc.yml
    add_note: false
    folders:
      - name: Top Level
        description: |
          Below are results that are in the base directory.
        table: |
          | Filename    | Description |
          |-------------|-------------|
          | rgi-20.{csv,eps,png}  | Heatmap representations as text and images, see [RGI - Heatmap](https://github.com/arpcard/rgi#generating-heat-maps-of-rgi-main-results) for more details |
          | rgi.tsv  | A merged TSV file with `rgi` results from all samples |
      - name: rgi
        description: |
          Below is a description of the _per-sample_ results from [RGI](https://github.com/arpcard/rgi).
        table: |
          | Filename                 | Description |
          |--------------------------|-------------|
          | &lt;SAMPLE_NAME&gt;.json  | A JSON file with `rgi` results |
          | &lt;SAMPLE_NAME&gt;.txt  | A tab-delimited file with `egi` results, see [RGI - Output Details](https://github.com/arpcard/rgi#rgi-main-tab-delimited-output-details) for more details |
  citations:
    - rgi
