name: abritamr
description: A NATA accredited tool for reporting the presense of antimicrobial resistance genes
icon: false
keywords:
  - TAGS
modules:
  - LIST_OF_MODULES
input:
  - meta:
    type: map
    description: |
      Groovy Map containing sample information
      e.g. [ id:'test', single_end:false ]
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
docs:
  meta:
    title: abritamr
    description: >
      A Bactopia Tool which uses...
  introduction: |
      The `abritamr` module uses...
  output:
    tree: |

    add_note: false
    folders:
      - name: Top Level
        description: |
          Below are results that are in the base directory.
        table: |
          | Filename    | Description |
          |-------------|-------------|
          |  |  |
      - name: abritamr
        description: |
          Below is a description of the _per-sample_ results from [abritamr](SUBWORKFLOW_LINK).
        table: |
          | Filename              | Description |
          |-----------------------|-------------|
          |  |  |
  citations:
    - add to citations.yml
