name: ectyper
description: In-silico prediction of _Escherichia coli_ serotype
introduction: |
  The `ectyper` module used [ECTyper](https://github.com/phac-nml/ecoli_serotyping) to conduct
  _in silico_ prediction of serotype for _Escherichia coli_ genomes. It uses the genome assemblies
  tp provide basic species identification and the predicted _E. coli_ serotype (e.g. O174:H21).
icon: false
tags:
  - Escherichia coli
  - fasta
  - serotype
modules:
  - ectyper
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - fasta:
      type: file
      description: A Staphylococcus aureus fasta file.
      pattern: "*.{fna,fna.gz}"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - tsv:
      type: file
      description: A summary of the per-sample ectyper result
      pattern: "*.tsv"
  - merged_tsv:
      type: file
      description: A merged TSV of all ectyper result files
      pattern: "ectyper.tsv"
  - txt:
      type: file
      description: Allele report generated from BLAST results
      pattern: "*.txt"
  - versions:
      type: file
      description: File containing software versions
      pattern: 'versions.yml'
citations:
  - ectyper
