name: spatyper
description: Computational method for finding spa types in Staphylococcus aureus
keywords:
  - fasta
  - spatype
  - Staphylococcus aureus
modules:
  - spatyper
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - fasta:
      type: file
      description: FASTA assembly file
      pattern: "*.{fasta,fasta.gz,fa,fa.gz,fna,fna.gz}"
  - repeats:
      type: file
      description: spa repeat sequences in FASTA format (Optional)
      pattern: "*.{fasta}"
  - repeat_order:
      type: file
      description: spa types and order of repeats (Optional)
      pattern: "*.{txt}"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software versions
      pattern: 'versions.yml'
  - tsv:
      type: file
      description: Per-sample summary of the spaTyper assessement
      pattern: "*.tsv"
  - merged_tsv:
      type: file
      description: A merged summary of the spaTyper assessement
      pattern: "spatyper.tsv"
