name: All Bactopia Tests (Docker)

on: workflow_dispatch
  #schedule:
    # At 01:30 on Monday and Thursday
    #- cron:  '30 1 * * 1,4'

jobs:
  pytest-bactopia:
    runs-on: olaf
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout bactopia/bactopia
        uses: actions/checkout@v2
        with:
          path: ${{ github.run_id }}/bactopia

      - name: Setup ENV variables
        run: |
          echo "BACTOPIA_CI=/data/storage/bactopia-ci" >> $GITHUB_ENV
          echo "BACTOPIA_CONDA=/data/storage/bactopia-ci/envs" >> $GITHUB_ENV
          echo "BACTOPIA_TESTS=/data/storage/bactopia-ci/bactopia-tests/data" >> $GITHUB_ENV
          echo "BACTOPIA_WORKSPACE=${GITHUB_WORKSPACE}/${{ github.run_id }}/bactopia" >> $GITHUB_ENV
          echo "BACTOPIA_TMP=/tmp/gh-runner-${{ github.run_id }}" >> $GITHUB_ENV
          mkdir /tmp/gh-runner-${{ github.run_id }}

      - name: Run Bactopia Tests (per module)
        run: |
          source /data/storage/bactopia-ci/miniconda3/etc/profile.d/conda.sh
          conda activate bactopia-ci
          cd ${{ env.BACTOPIA_WORKSPACE }}
          ls modules/local/bactopia | xargs -I {} -P 15 -n 1\
              bash -c 'BACTOPIA_ARGS="-profile docker --test_data_dir ${{ env.BACTOPIA_TESTS }}" TMPDIR=${{ env.BACTOPIA_TMP }} \
                       pytest --wt 5 --symlink --kwdof -o "testpaths=tests modules/local/bactopia" --tag {}'

      - name: Run Bactopia Tools Tests (per subworkflow)
        run: |
          source /data/storage/bactopia-ci/miniconda3/etc/profile.d/conda.sh
          conda activate bactopia-ci
          cd ${{ env.BACTOPIA_WORKSPACE }}
          ls subworkflows/local/ | xargs -I {} \
              bash -c 'BACTOPIA_ARGS="-profile docker  --test_data_dir ${{ env.BACTOPIA_TESTS }}" TMPDIR=${{ env.BACTOPIA_TMP }} \
                       pytest --wt 5 --symlink --kwdof -o "testpaths=tests subworkflows/local/" --tag {}'

      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: logs-debian
          path: |
            /tmp/gh-runner-${{ github.run_id }}/pytest_workflow_*/*/log.out
            /tmp/gh-runner-${{ github.run_id }}/pytest_workflow_*/*/log.err
            
      - name: Cleanup
        if: always()
        run: rm -rf ${{ github.run_id }} /tmp/gh-runner-${{ github.run_id }}
