name: All Bactopia Tests (Singularity)

on: workflow_dispatch
  #schedule:
    # At 01:30 on Monday and Thursday
    #- cron:  '30 1 * * 1,4'

jobs:
  pytest-bactopia:
    runs-on: olaf
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout bactopia/bactopia
        uses: actions/checkout@v2
        with:
          path: ${{ github.run_id }}/bactopia

      - name: Run Bactopia Tests (per module)
        run: |
          cd ${{ github.run_id }}/bactopia
          BACTOPIA_CI=/data/storage/bactopia-ci
          BACTOPIA_WORKSPACE="${GITHUB_WORKSPACE}/${{ github.run_id }}"
          source ${BACTOPIA_CI}/miniconda3/etc/profile.d/conda.sh
          conda activate bactopia-ci
          uname -a && env
          mkdir /tmp/${{ github.run_id }}
          cd ${BACTOPIA_WORKSPACE}/bactopia
          BACTOPIA_ARGS="-profile singularity --singularity_cache ${BACTOPIA_CI}/envs/singularity --test_data_dir ${BACTOPIA_CI}/bactopia-tests/data" TMPDIR=/tmp/${{ github.run_id }} pytest --wt 20 --symlink --kwdof --ignore conda/ --ignore .git/ --ignore .github/ --tag bactopia

      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: logs-debian
          path: |
            /tmp/${{ github.run_id }}/pytest_workflow_*/*/log.out
            /tmp/${{ github.run_id }}/pytest_workflow_*/*/log.err
            
      - name: Cleanup
        if: always()
        run: rm -rf ${{ github.run_id }} /tmp/${{ github.run_id }}
