name: bactopia-commands

on:
  push:
    branches: [ master, main, dev ]
  pull_request:
    branches: [ master, main, dev ]
    
jobs:
  bactopia-commands:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout bactopia/bactopia
        uses: actions/checkout@v2

      - name: Pull Bactopia
        uses: actions/checkout@v2
        with:
          repository: bactopia/bactopia-tests
          path: bactopia-tests

      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: bactopia
          auto-activate-base: false

      - name: Setup Bactopia Environment
        run: bash ${GITHUB_WORKSPACE}/bin/gh-actions/setup-bactopia-env.sh ${CONDA} ${GITHUB_WORKSPACE} 1

      - name: Environment Information
        run: uname -a && env

      - name: Test bactopia commands
        run: |
          TMPDIR=~ pytest --symlink --kwdof --tag bactopia_help

      - name: Test bactopia search
        run: |
          TMPDIR=~ pytest --symlink --kwdof --tag bactopia_search

      - name: Test bactopia prepare
        run: |
          TMPDIR=~ pytest --symlink --kwdof --tag bactopia_prepare
