name: Test Bactopia Commands

on:
  push:
    branches: [ master, main, dev ]
  pull_request:
    branches: [ master, main, dev ]
    
jobs:
  bactopia-commands:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout bactopia/bactopia
        uses: actions/checkout@v2

      - name: Pull Bactopia
        uses: actions/checkout@v2
        with:
          repository: bactopia/bactopia-tests
          path: bactopia-tests

      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: bactopia
          auto-activate-base: false

      - name: Setup Bactopia Environment
        run: bash ${GITHUB_WORKSPACE}/bin/gh-actions/setup-bactopia-env.sh ${CONDA} ${GITHUB_WORKSPACE} 1

      - name: Environment Information
        run: uname -a && env && bactopia --version

      - name: Test bactopia commands
        run: |
          TMPDIR=~ pytest --symlink --kwdof --ignore conda/ --tag bactopia_help

      - name: Test bactopia search
        run: |
          TMPDIR=~ pytest --symlink --kwdof --ignore conda/ --tag bactopia_search

      - name: Test bactopia prepare
        run: |
          TMPDIR=~ pytest --symlink --kwdof --ignore conda/ --tag bactopia_prepare

      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: logs-debian
          path: |
            ~/pytest_workflow_*/*/log.out
            ~/pytest_workflow_*/*/log.err

      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: logs-bactopia-tools
          path: |
            ~/pytest_workflow_*/*/log.out
            ~/pytest_workflow_*/*/log.err
            ~/pytest_workflow_*/*/.nextflow.log
            ~/pytest_workflow_*/*/work/**/*.log
            ~/pytest_workflow_*/*/work/**/*.err
            ~/pytest_workflow_*/*/work/**/*.out
            ~/pytest_workflow_*/*/work/**/*stderr.txt
            ~/pytest_workflow_*/*/work/**/*stdout.txt
