name: Conda Personal Build (Manual)
on: workflow_dispatch
jobs:
  conda-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout bactopia/bactopia
        uses: actions/checkout@v3
        with:
          ref: dev

      - name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          activate-environment: anaconda-client-env
          use-mamba: true

      - name: Build and Push 
        run: |
          # Start build
          conda install -c conda-forge -c bioconda anaconda-client conda-build conda-verify
          cd data/conda/ && mamba build -c conda-forge -c bioconda -c defaults --output-folder . . 
          anaconda upload --force ./noarch/*.tar.bz2
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
