name: Conda Personal Build (Manual)
on: workflow_dispatch
jobs:
  conda-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout bactopia/bactopia
        uses: actions/checkout@v3
        with:
          ref: dev

      - name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          activate-environment: anaconda-client-env
          use-mamba: true

      - name: Build and Push 
        run: |
          # Download datasets
          mamba --version
          VERSION=$(grep -E "^\s+version = " nextflow.config | sed "s/.*version = '//;s/'//")
          wget --quiet -O data/datasets/amrfinderdb.tar.gz https://datasets.bactopia.com/datasets/v${VERSION}/amrfinderdb.tar.gz
          wget --quiet -O data/datasets/mlst.tar.gz https://datasets.bactopia.com/datasets/v${VERSION}/mlst.tar.gz
          ls -lh .
          ls -lh data/datasets/
          # Start build
          conda install -c conda-forge -c bioconda anaconda-client conda-build conda-verify
          cd conda/recipe/ && mamba build -c conda-forge -c bioconda -c defaults --output-folder . . 
          anaconda upload --force ./noarch/*.tar.bz2
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
