name: Conda Personal Build (Manual)
on: workflow_dispatch
jobs:
  conda-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout bactopia/bactopia
        uses: actions/checkout@v2
        with:
          ref: dev

      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: conda-build
          auto-activate-base: false

      - name: Build and Push 
        run: |
          conda install -c conda-forge -c bioconda anaconda-client conda-build conda-verify
          cd conda/recipe/ && conda build -c conda-forge -c bioconda -c defaults --output-folder . . && anaconda upload --force ./linux-64/*.tar.bz2
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
