name: Test Bactopia Tutorial

on: workflow_dispatch
  #schedule:
    # At 01:30 on Monday and Thursday
    #- cron:  '30 1 * * 1,4'

jobs:
  bactopia-tutorial:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout bactopia/bactopia
        uses: actions/checkout@v2
        with:
          path: ${{ github.run_id }}/bactopia

      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: bactopia-dev
          auto-activate-base: false

      - name: Setup Bactopia Environment
        run: conda install -y -c rpetit3 -c conda-forge -c bioconda rpetit3::bactopia

      - name: Environment Information
        run: uname -a && env && bactopia --version

      - name: Free up Disk Space
        run: bash ${GITHUB_WORKSPACE}/bin/gh-actions/free-disk-space.sh

      - name: Conda Profile
        run: |
          bash ${GITHUB_WORKSPACE}/bin/gh-actions/run-tutorial.sh

      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: logs-bactopia
          path: |
            ${GITHUB_WORKSPACE}/bactopia-tutorial/.nextflow.log
            ${GITHUB_WORKSPACE}/bactopia-tutorial/work/**/*.log
            ${GITHUB_WORKSPACE}/bactopia-tutorial/work/**/*.err
            ${GITHUB_WORKSPACE}/bactopia-tutorial/work/**/*.out
            ${GITHUB_WORKSPACE}/bactopia-tutorial/work/**/*stderr.txt
            ${GITHUB_WORKSPACE}/bactopia-tutorial/work/**/*stdout.txt
